# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18e3006cf043ddce577d3a052d2dea39262d9d9ae6271cd847e95304d1a30fa74cd6d83e8a7a4bdb6ef63aa9a3a53aefebe9005fb5ac1835e03ef31787a4b86

test:
  secret_key_base: e0a723e53871ff9228accf32ff5d40597535cf7ccb4e230540d7f1d6c6a962d607e0974b660e1e9c172a3e0af6c550e1875a69747ed7af3cd5a6e00d24b011f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
